#! /bin/sh

resolution=1920x1080
wallpaper_path=~/Images/Wallpaper.jpg

killall sxhkd
killall polybar
sxhkd &
dunst &
xrandr -s $resolution
xmodmap -e 'keycode 94 = Escape'
feh --bg-fill $wallpaper_path
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config normal_border_color "#A0AEC0"
bspc config active_border_color "#FFFFFF"
bspc config focused_border_color "#FFFFFF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
